### ISSUE TITLE
Support login persistence

### ISSUE THREAD

**Issue by claell** [diezo/Ensta#111]
Persisting login information might be a good idea. Otherwise, the account appears to be signed in from scratch for every new creation of the `Mobile()` class, right?

**Comment by diezo** [comment]
That's not the case. Ensta auto-saves login sessions inside ```ensta-sessions``` directory by default while using the Mobile class. Whenever you create a new instance of ```Mobile()```, it'll load the saved session rather than creating a new one until the saved session expires.

**Comment by diezo** [comment]
```Mobile``` class will calculate the hash of username and password and find it's corresponding session file. Then, it'll use that session until it expires. The credentials will only be used to verify the saved session files and will be used to create new sessions when the existing ones expire.

**Comment by diezo** [comment]
If you don't wish to explicitly provide your credentials and rather use a saved session, you can do so by passing the contents of the session file as a string to ```Mobile``` class's ```session_data``` parameter. Hope that helps.
