### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by juanpnvd** [diezo/Ensta#14]
Would be awesome to have proxy support natively, thank you.

**Comment by juanpnvd** [comment]
Thank you, it works great! By any chance, do you know how much followers i can scrape in one go, or how the rate limits works right now? I want to be careful.

**Comment by diezo** [comment]
Earlier, I managed to fetch 2,000 followers in one go (then I stopped the program).

As of now, I don't have an exact estimate on what are the limits, but you can experiment using a dummy account.

To be on the safe side, you can add time limits between requests (eg. fetching 50-60 followers then waiting for some time).

**Comment by juanpnvd** [comment]
Thank you for your guidance, keep up the great work!
