### ISSUE TITLE
Host.__init__() missing 1 required positional argument: 'password'

### ISSUE THREAD

**Issue by jshen340** [diezo/Ensta#16]
Hi! I'm just starting out, and I'm trying to get my login to work through the host. I keep running into this error:
 
 File "C:\Users\python\login.py", line 4, in <module>
    host = Host(ID)
           ^^^^^^^^
TypeError: Host.__init__() missing 1 required positional argument: 'password'

Here is the code I've entered; I can't figure out what is wrong.

`from ensta import Host, NewSessionID

ID = NewSessionID("*", "*")
host = Host(ID)`

What do you advise I do? Thank you in advance!

**Comment by diezo** [comment]
Hi. I've passed some major updates recently to make the usage even more easier. Now, you don't need to generate new session id yourself. Instead, Host class will handle it automatically for you.

Here's the code you need:
```py
from ensta import Host

host = Host(username, password)
```
