### ISSUE TITLE
Multiaccounting

### ISSUE THREAD

**Issue by juanpnvd** [diezo/Ensta#20]
Would love to be able to manage a few or more accounts

**Comment by diezo** [comment]
Sounds like a great feature to have.

One way you can use multiple accounts inside your program is by creating multiple instances of the host class, each with it's own login credentials.

Here's what I mean:
```py
from ensta import Host

account1 = Host(username, password, file="session1.txt")  # 'Account1' session will be stored inside 'session1.txt'

account2 = Host(username, password, file="session2.txt")

account1.follow("cristiano")
account2.follow("leomessi")
```

Btw, what's your own opinion?

**Comment by juanpnvd** [comment]
Thank you for answering. I've done like you said but when it comes to do the second account it logins correctly but doesn't bring any followers. I get NoneType object has no attribute 'full_name'. The first account logged in always works correctly.

**Comment by diezo** [comment]
Can you give me the code? I'll test it on my machine.

**Comment by diezo** [comment]
I'm not quite sure what you mean by "any account has been blocked".

Did you mean to say if it's possible to check whether you've been blocked by someone or not?

If so, you can simply fetch their profile using guest mode first, and then do the same using Host Mode. If host doesn't successfully return the profile of that user while guest mode does, that should mean you've been blocked.

**Comment by juanpnvd** [comment]
I'm sorry for the misunderstanding. English is not my native. I mean if my account has been disabled by Instagram.

**Comment by diezo** [comment]
If your account has been suspended by Instagram, you may not be able to log in and ensta may raise Authentication Error Exception. Or if it has been restricted, you may not be able to perform certain actions whether through ensta or your browser.

The best way to validate this is by logging in into your account through your browser and check if everything's working fine.

If you have any other feature suggestions which I can implement in ensta, please mention them here. Thankyou
