### ISSUE TITLE
No attribute for Profile Category

### ISSUE THREAD

**Issue by lazyaccountant** [diezo/Ensta#26]
Hi diezo,

Thanks for the project. This has to be fastest Instagram API I have used. I noticed the Profile class has no category attribute. Is there a way to also get the Instagram profile category?

**Comment by diezo** [comment]
Hi @lazyaccountant 

Thankyou for using ensta. The profile class already has category attributes such as [personal/professional/business](https://github.com/diezo/Ensta/blob/master/ensta/containers/Profile.py#L14-L15) and [public/private account type](https://github.com/diezo/Ensta/blob/master/ensta/containers/Profile.py#L18).

If you mean something else, please do mention it here.

**Comment by lazyaccountant** [comment]
Some instagram accounts hve category name in their profile i.e. Fashion Model, Sportsperson, etc. That's what I was referring to

**Comment by diezo** [comment]
I've added the attribute in v4.6

1. Update ensta: ```pip install ensta --upgrade```
2. Here's the code
```py
from ensta import Guest

guest = Guest()
print(guest.profile("cristiano").category_name)
```

**Comment by lazyaccountant** [comment]
Blessings and Gratitude.
