### ISSUE TITLE
any fiture?

### ISSUE THREAD

**Issue by yekayee** [diezo/Ensta#29]
can post / comment or liking post?

**Comment by yekayee** [comment]
or update profile

**Comment by diezo** [comment]
to like/unlike individual posts:
```py
from ensta import Host

host = Host(username, password)
post = host.post("https://www.instagram.com/p/CzeSdT8oZbA/")

post.like()
post.unlike()
```

or to fetch posts of specific username:
```py
from ensta import Host

host = Host(username, password)
posts = host.posts("cristiano", 10)  # replace '10' with '0' if you want to fetch all posts

for post in posts:
    caption = post.caption_text
    like_count = post.like_count

    post.like()
    post.unlike()
```

to update profile:
```py
from ensta import Host

host = Host(username, password)

host.change_bio("hello")
host.change_display_name("John Smith")
```

**Comment by yekayee** [comment]
can update username or avatar and post photo ?

**Comment by diezo** [comment]
to post photo:
```python
from ensta import Host

host = Host(username, password)

host.upload_post(
    photo_path="Picture.jpg",
    caption="Travelling 🌆",
)
```

to upload reel:
```python
from ensta import Host

host = Host(username, password)

host.upload_reel(
    video_path="Video.mp4",
    thumbnail_path="Thumbnail.jpg",
    caption="Enjoying the winter! ⛄"
)
```

I'm working on posting comments, updating username and profile picture.

**Comment by yekayee** [comment]
what about avatar? and change username

**Comment by diezo** [comment]
ensta is based on instagram's web api and as far as i know, avatar is only available on the mobile version. i'll still search if there's a workaround for that.

and i'm currently working on username & profile picture. you'll see the implementation very soon.

**Comment by pafke2** [comment]
Hey, can we scrap all user's reels?

**Comment by diezo** [comment]
you can scrape all the posts of a user. the code is given in the readme file.

then, you can check the post type to check if it's a reel or picture.

**Comment by HCWcoder** [comment]
@diezo Man im glad i found you, i was a dev in instapy and im back now i would like to contribute and updating helping you

**Comment by diezo** [comment]
hi @HCWcoder

would you like to contribute to ensta?

**Comment by diezo** [comment]
hi @HCWcoder

i've seen your library instapy and it's really useful for python devs 

do you mean you would like to contribute to ensta to make further improvements?

it would be great to have you onboard!

**Comment by diezo** [comment]
hi @HCWcoder

it would be great to have you as a contributor at ensta.

**Comment by diezo** [comment]
@HCWcoder great to hear that you are in. are you comfortable joining my workspace on slack? we'll have rest of the conversation there.
https://diezosworkspace.slack.com/

**Comment by HCWcoder** [comment]
- you need to add me to the team: 

`jean.pierre.s.waked@gmail.com doesn’t have an account on this workspace.`

**Comment by diezo** [comment]
@HCWcoder i've added you to the workspace. please check if you've received the invitation.
