### ISSUE TITLE
Error AttributeError: 'Guest' object has no attribute 'get_biography'

### ISSUE THREAD

**Issue by lucio97** [diezo/Ensta#3]
using example 2 .py give me error in object

 **.py code:**
```python
from ensta import Guest
guest = Guest()
biography = guest.get_biography("cristiano")
print(biography)
```

**output:**
```python
 Traceback (most recent call last):
  File "REDACTED\test2.py", line 4, in <module>
    biography = guest.get_biography("cristiano")
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Guest' object has no attribute 'get_biography'
```

What's happening?

thanks

**Comment by diezo** [comment]
If I'm not wrong, you're talking about the example given in README.md file.

Individual functions are removed from the latest version. Now you can get someone's profile object and then extract information  from that object according to your needs.

Here's the updated code:
```py
from ensta import Guest

guest = Guest()
profile = guest.profile("ronaldo")  # Profile object

print(profile.biography)
print(profile.full_name)
print(profile.follower_count)
```

Note: profile() function returns None if request was unsuccessful. So, do add a condition block to check if profile is None when using in production.

Let me know if that solved your issue.

Thankyou
