### ISSUE TITLE
Different endpoint for followers

### ISSUE THREAD

**Issue by juanpnvd** [diezo/Ensta#39]
hi, would be cool if you could add the endpoint of gql in chunk, to me i get more followers this way than with v1. and something like getting the end cursor and continue with a different account. sorry if its hard to understand. english is not my native.

**Comment by diezo** [comment]
i understand you would like to get followers in a specific chunk length & be able to fetch the list again with specified index.

i've added it to my todo list and you'll soon be able to do so with ensta.

thank you for the suggestion!
