### ISSUE TITLE
FEATURE REQUEST: Alt text for photo posts

### ISSUE THREAD

**Issue by JoeD4321** [diezo/Ensta#40]
Could you add the ability for add "Alternate Text" to photo posts, for the blind and other accessibility issues?

Thanks

**Comment by diezo** [comment]
thanks for the suggestion. i'll add this feature within a few hours.

**Comment by diezo** [comment]
this feature has been implemented. here's the code:

```python
from ensta import Host

host = Host(username, password)

upload = host.get_upload_id("Picture.jpg")

host.upload_photo(
    upload,
    caption="Travelling 🌆",
    alt_text="photo of a dog"
)
```

same goes for uploading reels, just specify the ```alt_text``` parameter.

thank you
