### ISSUE TITLE
Issue with follower list

### ISSUE THREAD

**Issue by lorenzosantarsieri** [diezo/Ensta#41]
When running this code, there's an error 

from ensta import Host

host = Host(username, password)

followers = host.followers("leomessi", count=100)  # Want full list? Set count to '0'
followings = host.followings("leomessi", count=100)  # Want full list? Set count to '0'

for user in followers:
    print(user.username)

for user in followings:
    print(user.username)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python310\site-packages\ensta\SessionHost.py:334, in SessionHost.followers(self, identifier, count)
    323 try:
    324     yield FollowPerson(
    325         has_anonymous_profile_picture=each_item["has_anonymous_profile_picture"],
    326         user_id=each_item["pk"],
    327         username=each_item["username"],
    328         full_name=each_item["full_name"],
    329         is_private=each_item["is_private"],
    330         is_verified=each_item["is_verified"],
    331         profile_picture_url=each_item["profile_pic_url"],
    332         badges=each_item["account_badges"],
    333         third_party_downloads_enabled=each_item["third_party_downloads_enabled"],
--> 334         is_possible_scammer=each_item["is_possible_scammer"]
    335     )
    337 except KeyError:

KeyError: 'is_possible_scammer'

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
Cell In[172], line 1
----> 1 for user in followers:
      2     try:
      3         print(user.username)

File ~\AppData\Roaming\Python\Python310\site-packages\ensta\SessionHost.py:338, in SessionHost.followers(self, identifier, count)
    324             yield FollowPerson(
    325                 has_anonymous_profile_picture=each_item["has_anonymous_profile_picture"],
    326                 user_id=each_item["pk"],
   (...)
    334                 is_possible_scammer=each_item["is_possible_scammer"]
    335             )
    337         except KeyError:
--> 338             raise APIError()
    340         generated_count += 1
    342 if (generated_count < count or count == 0) and "next_max_id" in response_json:

APIError: None

**Comment by diezo** [comment]
hi

please update ensta using ```pip install ensta --upgrade``` and run the code again.

also, if you can, please attach a screenshot of the error so that it can be more understandable.

thank you

**Comment by diezo** [comment]
hi, the bug has been fixed. please update ensta using: ```pip install ensta --upgrade```

thanks
