### ISSUE TITLE
can u add Instagram account checker with api methode

### ISSUE THREAD

**Issue by Zhukov-Z** [diezo/Ensta#44]
can u add Instagram account checker with api methode

**Comment by diezo** [comment]
do you mean to check if the given username password combination is correct or to check whether an Instagram account with the specified username/userid exists.

**Comment by Zhukov-Z** [comment]
given username password combination is correct or to check,
example :
Manutd:ggmu123 is correct
mancity:mancity321 password wrong

**Comment by Zhukov-Z** [comment]
> do you mean to check if the given username password combination is correct or to check whether an Instagram account with the specified username/userid exists?

given username password combination is correct or to check,
example :
Manutd:ggmu123 is correct
mancity:mancity321 password wrong

**Comment by diezo** [comment]
yes you can easily do that with ensta. just initialise host class with the given credentials and check if it raises any exception.

here's the code:
```py
from ensta import Host
from ensta.lib.Exceptions import AuthenticationError

success: bool

try:
    host = Host(username, password)
    success = True

except AuthenticationError as e:
    success = False
    print(e)  # it can be "User doesn't exist." or "Invalid password."

print(success)
```
