### ISSUE TITLE
Problem with importing Ensta

### ISSUE THREAD

**Issue by done1892** [diezo/Ensta#5]
Hi!
I would like to try some features of your library but when I import ensta i got this error: 
![Catt](https://github.com/diezo/Ensta/assets/35931906/4b2bc8df-f3f2-44f9-9761-4f939596a896)

So that makes your library unusable.. i'm missing some requirements?

**Comment by diezo** [comment]
I think that's an issue with your python version. You are using Python 3.8 (that's an old version).

Please upgrade your Python Version from [here](https://www.python.org/downloads/) and try using this library again.

**Comment by done1892** [comment]
Hi! thank you for your answer.
I updated the python version to 3.11.4 as you told me but issues remain:
![C](https://github.com/diezo/Ensta/assets/35931906/488efd50-a029-4a3e-a36f-f4e3deeaae83)

**Comment by done1892** [comment]
Requirements issues have been solved: now i get no error for imports, etc.
But when i try to fetch CR7's profile information i got NoneType back as you can see.

![Cattura2](https://github.com/diezo/Ensta/assets/35931906/7189f89f-2a52-45b0-acbf-e48a3114c94e)

How can i fix it?

**Comment by diezo** [comment]
**profile()** returns None when ensta fails to fetch data from Instagram. And that's probably because of Network Issues.

It's the same type of error as it previously was. Have you tried using ensta with a VPN or Proxy?

How did you solved the requirements issue?

**Comment by done1892** [comment]
> How did you solve the requirements issue btw?
I created a virtual env with the python version you specified (3.11.4) and i installed all the requirements.

I'll make you know if changing wifi, usining vpn, etc., work and lead me to result. Thank you for all suggestions!!

**Comment by diezo** [comment]
Hi.

I'm glad that solved your issue. Can you let me know what exactly was wrong there?

Was it something wrong with the library?
