### ISSUE TITLE
ModuleNotFoundError with Cryptodome in PasswordEncryption.py

### ISSUE THREAD

**Issue by lihsimi** [diezo/Ensta#52]
When running `PasswordEncryption.py`, an error is prompted: `ModuleNotFoundError: No module named 'Cryptodome'`.

The error disappears when I replace all instances of `from Cryptodome` with `from Crypto` in the `PasswordEncryption.py` file.

**Comment by diezo** [comment]
i'll look into this issue and find a better alternative to ```cryptodome```.

**Comment by juanep97** [comment]
Installing pycryptodomex solved it for me.

**Comment by diezo** [comment]
i've replaced pycryptodome with cryptography. now, everything should work smoothly.
