### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by q1179336367** [diezo/Ensta#59]
username='xxxx'
password='xxxx'
from ensta import Host

host = Host(username, password)
profile = host.profile("leomessi")

print(profile.biography)

Traceback (most recent call last):
  File "F:/ys_projecct/pydemo1/spider_proxy/spider.py", line 92, in <module>
    from ensta import Host
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ensta\__init__.py", line 1, in <module>
    from ensta.Guest import Guest
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ensta\Guest.py", line 6, in <module>
    from .containers.Profile import Profile
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ensta\containers\__init__.py", line 2, in <module>
    from .Profile import Profile
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ensta\containers\Profile.py", line 5, in <module>
    class Profile:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\ensta\containers\Profile.py", line 24, in Profile
    pronouns: list[str] = None,
TypeError: 'type' object is not subscriptable

**Comment by diezo** [comment]
you just have to download the latest version of python from [here](https://www.python.org/downloads/) and you should be good to go.

**Comment by diezo** [comment]
please update me if that worked.

**Comment by q1179336367** [comment]
python 3.8 is not supported. Do I need to update to 3.12？

**Comment by q1179336367** [comment]
> 你只需要从[这里](https://www.python.org/downloads/)下载最新版本的 python就可以了。

不支持 python 3.8。需要更新到3.12吗？

**Comment by q1179336367** [comment]
> 如果有效，请更新我。

{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/?next=/api/v1/fbsearch/reels_serp/%253Fsearch_surface%253Dclips_serp_page%2526reels_page_index%253D1%2526timezone_offset%253D28800%2526has_more_reels%253Dtrue%2526count%253D30%2526query%253Dhero%2526reels_max_id%253D%2526next_max_id%253D%2526rank_token%253D%2526page_index%253D1%2526page_token%253D%2526paging_token%253D%25257B%252522total_num_items%252522%25253A18%25257D', 'api_path': '/challenge/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True, 'flow_render_type': 0}, 'status': 'fail'}

**Comment by diezo** [comment]
> > You just need to download the latest version of python from [here .](https://www.python.org/downloads/)
> 
> Python 3.8 is not supported. Need to update to 3.12?

Yes you need to update to python v3.12

**Comment by diezo** [comment]
> > If it works please update me.
> 
> {'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/?next=/api/v1/fbsearch/reels_serp/%253Fsearch_surface%253Dclips_serp_page%2526reels_page_index%253D1%2526timezone_offset%253D28800%2526has_more_reels%253Dtrue%2526count%253D30%2526query%253Dhero%2526reels_max_id%253D%2526next_max_id%253D%2526rank_token%253D%2526page_index%253D1%2526page_token%253D%2526paging_token%253D%25257B%252522total_num_items%252522%25253A18%25257D', 'api_path': '/challenge/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True, 'flow_render_type': 0}, 'status': 'fail'}

Most probably your password is weak, you need to update your password to a stronger one.

**Comment by q1179336367** [comment]
> > > If it works please update me.
> > 
> > 
> > {'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/?next=/api/v1/fbsearch/reels_serp/%253Fsearch_surface%253Dclips_serp_page%2526reels_page_index%253D1%2526timezone_offset%253D28800%2526has_more_reels%253Dtrue%2526count%253D30%2526query%253Dhero%2526reels_max_id%253D%2526next_max_id%253D%2526rank_token%253D%2526page_index%253D1%2526page_token%253D%2526paging_token%253D%25257B%252522total_num_items%252522%25253A18%25257D', 'api_path': '/challenge/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True, 'flow_render_type': 0}, 'status': 'fail'}
> 
> Most probably your password is weak, you need to update your password to a stronger one.

The password is case-sensitive in English

**Comment by diezo** [comment]
try changing it to a stronger one. say greater than 12 digits including uppercase and lowercase letters as well as numbers and special characters. you know what i mean.

**Comment by q1179336367** [comment]
> try changing it to a stronger one. say greater than 12 digits including uppercase and lowercase letters as well as numbers and special characters. you know what i mean.
> 
> https://www.lastpass.com/features/password-generator

ensta.lib.Exceptions.AuthenticationError: User doesn't exist.              But the account exists, and I can use instagram_private_api just fine

**Comment by q1179336367** [comment]
> try changing it to a stronger one. say greater than 12 digits including uppercase and lowercase letters as well as numbers and special characters. you know what i mean.
> 
> https://www.lastpass.com/features/password-generator

And after I used the site to generate a password and change it, I was prompted challenge_required

**Comment by diezo** [comment]
maybe instagram has flagged the account you're using. try using a different account.

**Comment by q1179336367** [comment]
> maybe instagram has flagged the account you're using. try using a different account.

In that case, it doesn't seem any different than when I use instagram_private_api

**Comment by diezo** [comment]
it's just an easy-to-use third-party implementation of the existing Instagram API and not some magic. if Instagram has flagged your account, i cannot help you either.

the only possible solution you're left with is to use a different account and take precautions when using any instagram api library in future.

**Comment by diezo** [comment]
i hope you understand that ensta is a mere python implementation of the existing instagram api, and you **must** be careful while using such libraries.

if you want, you can join our [discord server](https://discord.com/invite/pU4knSwmQe) for any further assistance.
