### ISSUE TITLE
HTTP Response is not a valid JSON.

### ISSUE THREAD

**Issue by geweb7** [diezo/Ensta#61]
```
from ensta import Guest
guest = Guest()
profile = guest.profile("leomessi")
```

_ensta.lib.Exceptions.NetworkError: HTTP Response is not a valid JSON._

ensta: 5.0.3.9
python: 3.10.12

how do we debug to see the response?

**Comment by diezo** [comment]
most probably your IP is flagged. try switching to a different wifi network.

**Comment by diezo** [comment]
if that doesn't work either, you're left with using the host class instead, as guest doesn't always work.

**Comment by geweb7** [comment]
using proxy solved the problem, thanks!

it would be nice if there is some clue to resolve in error message

**Comment by diezo** [comment]
glad to hear that. i'll update the error message to reflect the solution as well.

have a great day
