### ISSUE TITLE
NetworkError("HTTP response doesn't include 'status' or 'users' node." when making list of followers

### ISSUE THREAD

**Issue by TastingSunsets** [diezo/Ensta#68]
Hi

I am trying to create a list of the followers of another public account (which I am following with the account I use to run the script). The target account has 3k+ followers, but I only ever manage to write about 2k followers to a .txt file. The code I am using is this:

```
from ensta import Host

host = Host("username", "password")

followers = host.followers("target_account_id", count=0)

with open("followers.txt", "w") as file:
    for user in followers:
        if user is not None and user.username is not None:
            file.write(user.username + "\n")
        else:
            file.write("\n")
```

The error I am getting is this one:
> Traceback (most recent call last):
>   File "/Users/tasting.sunsets/sandbox/ensta/followers.py", line 8, in <module>
>     for user in followers:
>   File "/opt/homebrew/lib/python3.11/site-packages/ensta/SessionHost.py", line 319, in followers
>     raise NetworkError("HTTP response doesn't include 'status' or 'users' node.")
> ensta.lib.Exceptions.NetworkError: HTTP response doesn't include 'status' or 'users' node.

Any suggestions? Thanks!

**Comment by diezo** [comment]
You're being rate limited. You should wait for a while before trying again.

I'm working on a cursor feature by which you'll be able to continue scraping the followers list where you left off the previous time.

**Comment by diezo** [comment]
thanks for the star. i'll add the cursor feature soon. in the meantime, you should take precautions like adding time intervals between requests, using the same session as stored in ```ensta-session.txt``` file until it expires and the best way is to use dummy accounts and not your main account. note that creating bot accounts may be against instagram's policies. so do check them before proceeding.
