### ISSUE TITLE
Either user doesn't exist or your password is too weak (change it to a stronger one)

### ISSUE THREAD

**Issue by kerimembel** [diezo/Ensta#70]
I get this error when I try to log in to the account. I changed my password to a stronger one but I still get this error.

**Comment by diezo** [comment]
1. Try switching to a different wifi network or use proxy
2. Make sure you use your username and not email.

If the issue still exists, please contact me on discord: @gitdiezo

**Comment by kerimembel** [comment]
Thanks for the quick reply. It works fine on my local network but when I try it on remote server I get this error. I guess I should use a proxy to fix this.

**Comment by diezo** [comment]
Yes that's right. You need to use a proxy because Instagram restricts the ips of common cloud providers.
