### ISSUE TITLE
Uploading error with external file path instead of local path

### ISSUE THREAD

**Issue by mohaimenulislamshawon** [diezo/Ensta#71]
I have tried to upload reels to Instagram with the file path of an external website video path. but didn't work, showing the errors. Is it only supporting local paths? or is there any way to upload via an external path?

**Comment by diezo** [comment]
only local path is supported. to make it work your way, you first have to download the video using python requests or any module you prefer and then use the local file to upload

**Comment by diezo** [comment]
@ettoreleandrotognoli can we add this feature to ensta? the post upload and reel upload methods will detect if the given path is local or remote. and if it's a remote url, it'll auto download the media from the given url and continue to upload it.

**Comment by ettoreleandrotognoli** [comment]
I'll start doing a simple download
But I think this issue can grown in the future, what about cache and proxy?
