### ISSUE TITLE
Can't auth

### ISSUE THREAD

**Issue by v0id-main** [diezo/Ensta#78]
File "/Users/voidmain/Desktop/Python Projects/Ensta/PasswordEncryption.py", line 22, in encrypt
    recipient_key = load_pem_public_key(data=decoded_public_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. MalformedFraming

**Comment by diezo** [comment]
you're using an older version of ensta. update it using ```pip install ensta --upgrade```

**Comment by v0id-main** [comment]
> you're using an older version of ensta. update it using `pip install ensta --upgrade`

I'm using the latest version. the problem occurs in the password encryption file, which was updated 2 weeks ago

**Comment by diezo** [comment]
have u edited the file? line 22 doesn't have that.
