### ISSUE TITLE
[Feature Request] edit link bio

### ISSUE THREAD

**Issue by standartwae** [diezo/Ensta#79]
thanks for provide this code, I hope the future update you can add feature for delete link bio, add link bio and edit link bio

**Comment by diezo** [comment]
Hi. Features related to bio links have been added to ```Mobile``` class including ```add_bio_link()```, ```remove_bio_link()``` and ```clear_bio_links()```. Please take a look at the Readme for all the code. I'll add the ```update_bio_link()``` method soon.
