### ISSUE TITLE
Follower info

### ISSUE THREAD

**Issue by Macerul** [diezo/Ensta#8]
Hi I'm sorry, I wold try to use your library but I have a question: can I save someone's public info from their follower list? What I would like to do is search a public account (without logging in) access their follower list and for each follower savings public info like number of follower, name, etc

**Comment by diezo** [comment]
Hi. Thanks for your interest in this library.

Fetching someone's follower/following list without logging in is impossible as Instagram doesn't allow that. You need to login using the `Host Class`.

Don't worry, your credentials are safe and it doesn't affect your account. **Ensta** uses selenium to log in as you would normally on your browser.

Here's the code you requested:
```py
from ensta import Host, NewSessionID

username = input("Username: ")
password = input("Password: ")

host = Host(NewSessionID(username, password))

target = input("Target username: ")
followers = host.followers(target, count=10)  # If you want to fetch the full list, don't specify 'count'

for user in followers:
    print(user.username)  # Access any data you want...
    print(user.full_name)
```

If you want the full profile data of each user, you can fetch that separately without logging in using the `Guest Class`:
```py
from ensta import Guest

guest = Guest()
profile = guest.profile("cristiano")  # Access full profile data

if profile is None:
    print("Unable to fetch user data")
else:
    print(profile.follower_count)
    print(profile.following_count)
```

Let me know if you have any questions. Thanks.

**Comment by Macerul** [comment]
> Hi. Thanks for your interest in this library.
> 
> Fetching someone's follower/following list without logging in is impossible as Instagram doesn't allow that. You need to login using the `Host Class`.
> 
> Don't worry, your credentials are safe and it doesn't affect your account. **Ensta** uses selenium to log in as you would normally on your browser.
> 
> > If you still don't want to use your primary account to login, you can create a dummy account (It takes only a few minutes to setup) and then use it to log into Ensta.
> 
> Here's the code you requested:
> 
> ```python
> from ensta import Host, NewSessionID
> 
> username = input("Username: ")
> password = input("Password: ")
> 
> host = Host(NewSessionID(username, password))
> 
> target = input("Target username: ")
> followers = host.followers(target, count=10)  # If you want to fetch the full list, don't specify 'count'
> 
> for user in followers:
>     print(user.username)  # Access any data you want...
>     print(user.full_name)
> ```
> 
> If you want the full profile data of each user (includes _follower_count_, _following_count_ and more), you can fetch that separately without logging in using the `Guest Class`:
> 
> ```python
> from ensta import Guest
> 
> guest = Guest()
> profile = guest.profile("cristiano")  # Access full profile data
> 
> if profile is None:
>     print("Unable to fetch user data")
> else:
>     print(profile.follower_count)
>     print(profile.following_count)
> ```
> 
> > ### NOTE:
> > If you encounter `ChallengeError` while logging in, it probably indicates that your password is weak and you need to change it to a strong one.
> 
> Let me know if you have any questions. Thanks.

Thank you so much for the detailed answer! Just one more question: suppose I want to retrieve the info about 1k follower. I can do it all at once or Instagram have a limit in this case? Or it's better if I collect like 50 follower info per time for different account?

**Comment by diezo** [comment]
> I can do it all at once or Instagram have a limit in this case?

You can fetch them all at once! The function internally fetches the list in chunks (35 at a time). So you don't need to worry about that.

You may wish to support **Ensta** by giving this repo a star. ❤️
Thanks!

**Comment by Macerul** [comment]
I'll definitely give it a go then, thank you so much once again!
