### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by rockwillck** [diezo/Ensta#86]
I'm trying to run Ensta off of a PythonAnywhere server (Python 3.10.5) but I'm encountering this issue:
`ensta.lib.Exceptions.AuthenticationError: Either user doesn't exist or your password is too weak (change it to a stronger one).`
I've tried changing my password and using email, but it only seems to raise this issue on one specific server for one specific account. Is this a bug?

**Comment by rockwillck** [comment]
I'm not entirely sure why but the issue appears to have resolved itself.

**Comment by diezo** [comment]
If this issue persists, you'll have to use residential proxies.
