### ISSUE TITLE
Couldn't fetch profiles info

### ISSUE THREAD

**Issue by Macerul** [diezo/Ensta#9]
Sorry to bother again, I tried the lib: I used the host mode to retrieve the follower list and then I switched to guest mode to retrieve the single profiles info. At first it worked but then in guest mode, when I ran the script for the third time, it couldn't fetch the profiles info. I'm guessing it's cause I did't use the same session but every time I generated a new sessionid so maybe Ig flagged me idk (I received emails from instagram stating that I was accessing from an unusual device) so I wonder how can I save the session once I run the script cause I tried saving it into a txt file but it didn't work. It would be very useful if you could give me an example.

**Comment by diezo** [comment]
> but then in guest mode, when I ran the script for the third time, it couldn't fetch the profiles info.

No session is required in `Guest Mode`. If you weren't able to fetch the profiles the 3rd time, I guess it's because of IP Block. You can try switching to a different WiFi Network or using a VPN/Proxy.

### Here's the answer to your second question:
Once you log in, you should save the sessionid. Here's how:
```py
from ensta import Host, NewSessionID

sessionid = NewSessionID("username", "password")

with open("session.txt", "w") as file:
    file.write(sessionid)
```


To load the sessionid:
```py
from ensta import Host

with open("session.txt", "w") as file:
    sessionid = file.read().strip()

host = Host(sessionid)
# continue...
```


Let me know if you have any further questions.
Thanks.

**Comment by Macerul** [comment]
It would be very appreciated if you could provide me a full solution so that I have a plan B in case something goes wrong. 
Again, thank you so much for your time and consideration!

**Comment by diezo** [comment]
Here's a script I wrote:
```py
from ensta import Host, NewSessionID
from ensta import Exceptions

username = ""
password = ""
sessionFile = "./session.txt"

with open(sessionFile, "r") as file:
    sessionid = file.read().strip()

try:
    host = Host(sessionid)

except Exceptions.SessionError:
    sessionid = NewSessionID(username, password)

    with open(sessionFile, "w") as file:
        file.write(sessionid)

    host = Host(sessionid)


host.profile("cristiano")
# continue...
```

Create a file named `session.txt` in the current directory before executing the script.

Also, upgrade **Ensta** by running:
```shell
pip install ensta==2.6
```

It'll fetch the session id from that file and try to log in. If login fails (means sessionid is expired or invalid), it'll generate a new sessionid and save it to that file, and use it in the future until it expires.

This way, you don't have to worry about recreating new sessionid when the existing one expires.

Do you have any other questions?
Thanks.

**Comment by Macerul** [comment]
> Here's a script I wrote for reference:
> 
> ```python
> from ensta import Host, NewSessionID
> from ensta import Exceptions
> 
> username = ""
> password = ""
> sessionFile = "./session.txt"
> 
> with open(sessionFile, "r") as file:
>     sessionid = file.read().strip()
> 
> try:
>     host = Host(sessionid)
> 
> except Exceptions.SessionError:
>     sessionid = NewSessionID(username, password)
> 
>     with open(sessionFile, "w") as file:
>         file.write(sessionid)
> 
>     host = Host(sessionid)
> 
> 
> host.profile("cristiano")
> # continue...
> ```
> 
> Create a file named `session.txt` in the current directory before executing the script.
> 
> Also, upgrade **Ensta** by running:
> 
> ```shell
> pip install ensta==2.7
> ```
> 
> It'll fetch the session id from that file and try to log in. If login fails (means sessionid is expired or invalid), it'll generate a new sessionid and save it to that file, and use it in the future until it expires.
> 
> This way, you don't have to worry about recreating new sessionid when the existing one expires.
> 
> Do you have any other questions? Thanks.

Thank you so much, it worked fine! I was wondering if the IP block is like permanent or I just have to wait cause with the host mode it worked perfectly fine but when I switched to guest mode I got the same issues 'unable to fetch user data'. So I was wondering if I just have to wait or idk try with another wifi network cause I don't have a vpn.

**Comment by diezo** [comment]
You're welcome, Macerul!

I'll have a look into the issue to check if it's IP Block or some other type of error. Btw, `Host Mode` also supports fetching profile data. So, you can use it if you need:

```py
host.profile("cristiano")  # just like guest.profile()
```

Btw I'm curious... What project are you working on? And what are your needs?

Thanks

**Comment by Macerul** [comment]
> You're welcome, Macerul!
> 
> I'll have a look into the issue to check if it's IP Block or some other type of error. And the IP block isn't permanent... Btw, `Host Mode` also supports fetching profile data. So, you can use it if you need:
> 
> ```python
> host.profile("cristiano")  # just like guest.profile()
> ```
> 
> Btw I'm curious... What project are you working on? And what are your needs?
> 
> Thanks

I'm using both cause I saw that host doesn't have all the attributes that I need like follower count, media count etc
Btw it's my university project I'm trying to collect info from profiles to distinguish fake profiles from autentic ones. I was going crazy cause it's not that easy cause Ig it's very scrict about data scraping so finding your lib was a true blessing before that I was entirely stuck!

**Comment by diezo** [comment]
That's an interesting idea.

I'm glad Ensta could help. Good luck with your project!
