### ISSUE TITLE
[DOC] Add FFMPEG requirement in documentation

### ISSUE THREAD

**Issue by loic-hamdi** [diezo/Ensta#90]
Add FFMPEG requirement in documentation:
`brew install ffmpeg`

**Comment by ettoreleandrotognoli** [comment]
ffmpeg is a indirect dependency that comes from moviepy

"The software FFMPEG should be automatically downloaded/installed (by imageio) during your first use of MoviePy (installation will take a few seconds)." https://pypi.org/project/moviepy/

I don't think we should add it, but I don't see any harm in add it too

**Comment by diezo** [comment]
Thanks for the suggestion @loic-hamdi. I'll add it in the readme as well as the docs.
