### ISSUE TITLE
Authentication not Working

### ISSUE THREAD

**Issue by nlkguy** [diezo/Ensta#94]
```
Traceback (most recent call last):
  File "/home/~~~~~~.py", line 8, in <module>
    profile = host.profile("leomessi")
  File "/home/~~~~/.local/lib/python3.10/site-packages/ensta/SessionHost.py", line 571, in profile
    return self.guest.profile(username, __session__=self.request_session)
  File "/home~~~~/.local/lib/python3.10/site-packages/ensta/Guest.py", line 191, in profile
    raise NetworkError("HTTP Response is not a valid JSON.")
ensta.lib.Exceptions.NetworkError: HTTP Response is not a valid JSON.
```

**Comment by diezo** [comment]
@nlkguy are you using ensta on the cloud? if yes, then you need to use good proxies. or maybe just try switching to a different wifi network.

**Comment by nlkguy** [comment]
sure will do.
I think it is the rate limit from Instagram. 

The same credentials are not working in any other network/IP .
but I tried a different host and it worked.

the problem with the old host resolved when I waited for a few hours

**Comment by diezo** [comment]
@nlkguy Yes. IG limits the actions on a specific IP address if it finds it suspicious. Make sure you don't use the same IP address for more than 5 accounts.
