### ISSUE TITLE
Resumable Download Followers

### ISSUE THREAD

**Issue by vhdm** [diezo/Ensta#95]
**Hi 👋, thank you very much for the practical package❤️, it is possible to get followers continuously with several different i.g accounts**

**Comment by diezo** [comment]
@vhdm You can use ```Mobile``` class to fetch followers/followings. That way you can save the last cursor value and resume from where you left off later on. I think the cursor value should also work across multiple accounts.

```python
from ensta import Mobile

mobile = Mobile(username, password)

followers = mobile.followers(someone)

for user in followers.list:
    print(user.username)

next_cursor = followers.next_cursor  # use this cursor next time to resume from here
```

Here's how to define the next_cursor value next time:
```python
followers = mobile.followers(someone, next_cursor=previous_cursor_value)
```
