### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by umutkamanoglu** [diezo/Ensta#97]
from ensta import Mobile
ImportError: cannot import name 'Mobile' from partially initialized module 'ensta' (most likely due to a circular import)

how can i fix this issue ?? 
i use "pip install ensta" command

**Comment by diezo** [comment]
I think you've named your main python script either "ensta.py" or "Mobile.py". Or maybe you already have a folder with such name.

**Comment by umutkamanoglu** [comment]
Yea. I change the file name and fix the issue thanks
